from pydantic import BaseModel, Field


# ==========================================================
# Requests
# ==========================================================

class ChatRequest(BaseModel):
    question: str = Field(
        ...,
        description="Question to ask about the indexed documents.",
        examples=["What is Docker?"],
    )


# ==========================================================
# Common Models
# ==========================================================

class Citation(BaseModel):
    source: str = Field(
        ...,
        description="Source document name.",
        examples=["docker-guide.pdf"],
    )

    page: str | int = Field(
        ...,
        description="Page number where the answer was found.",
        examples=[5],
    )


class BaseResponse(BaseModel):
    success: bool = Field(
        ...,
        description="Indicates whether the request was successful.",
        examples=[True],
    )

    message: str | None = Field(
        default=None,
        description="Optional response message.",
        examples=["Operation completed successfully."],
    )


# ==========================================================
# Chat
# ==========================================================

class ChatData(BaseModel):
    answer: str = Field(
        ...,
        description="Answer generated by the AI model.",
        examples=[
            "Docker is a containerization platform used to package and deploy applications."
        ],
    )

    citations: list[Citation] = Field(
        ...,
        description="Documents used to generate the answer.",
    )


class ChatResponse(BaseResponse):
    data: ChatData


# ==========================================================
# Upload
# ==========================================================

class UploadData(BaseModel):
    task_id: str = Field(
        ...,
        description="Background indexing task ID.",
        examples=["f3a1c2b4-98ab-4b0e-8123-acde12345678"],
    )

    status: str = Field(
        ...,
        description="Current indexing status.",
        examples=["processing"],
    )

    filename: str = Field(
        ...,
        description="Uploaded PDF filename.",
        examples=["docker-guide.pdf"],
    )


class UploadResponse(BaseResponse):
    data: UploadData


# ==========================================================
# Task Status
# ==========================================================

class TaskData(BaseModel):
    task_id: str = Field(
        ...,
        description="Background task ID.",
        examples=["f3a1c2b4-98ab-4b0e-8123-acde12345678"],
    )

    status: str = Field(
        ...,
        description="Current task status.",
        examples=["processing"],
    )


class TaskResponse(BaseResponse):
    data: TaskData


# ==========================================================
# Health Check
# ==========================================================

class HealthCheck(BaseModel):
    healthy: bool = Field(
        ...,
        description="Health status of the component.",
        examples=[True],
    )

    model: str | None = Field(
        default=None,
        description="LLM model name (if applicable).",
        examples=["llama3.2"],
    )

    documents: int | None = Field(
        default=None,
        description="Number of indexed documents (ChromaDB).",
        examples=[1243],
    )

    free_gb: int | float | None = Field(
        default=None,
        description="Available disk space in GB.",
        examples=[180],
    )


class HealthData(BaseModel):
    healthy: bool = Field(
        ...,
        description="Overall health status of the API.",
        examples=[True],
    )

    checks: dict[str, HealthCheck] = Field(
        ...,
        description="Health status of each system component.",
    )


class HealthResponse(BaseResponse):
    data: HealthData

class ConversationCreateRequest(BaseModel):
    title: str = "New Chat"


class ConversationRenameRequest(BaseModel):
    title: str    